server:
  port: 8099

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  config:
    import: classpath:dev-config.yml
  datasource:
    mysql:
      username: root
      password: ${datasource.mysql.password}
      url: jdbc:mysql://${myip}:13306/ai-agent-station-study?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: Retail_HikariCP
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1
    pgvector:
      username: postgres
      password: ${datasource.pgvector.password}
      url: jdbc:postgresql://${myip}:15432/postgres
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: Retail_HikariCP
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1
  ai:
    openai:
      base-url: ${ai.openai.base-url}
      api-key: ${ai.openai.api-key}
      chat:
        options:
          model: qwen3-max
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1536
    agent:
      auto-config:
        enabled: true
        client-ids: 6101
#        client-ids: 2101,2102,2103
#        client-ids: 4101,4102,4103,4104
#        client-ids: 5101,5102,5103,5104
#        client-ids: 3101,3102,3103,3104,4101,4102,4103,4104

# MyBatis 配置【如需使用记得打开】
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 小傅哥扳手通用组件配置
xfg:
  wrench:
    # 任务调度配置
    task:
      job:
        enabled: true
        pool-size: 5
        thread-name-prefix: "test-task-scheduler-"
        wait-for-tasks-to-complete-on-shutdown: true
        await-termination-seconds: 30
        refresh-interval: 30000
        clean-invalid-tasks-cron: "0 0/5 * * * ?"



baidu:
  api-key: ${baidu.apikey}


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml